### Get productos
GET http://localhost:5000/api/v1/productos

### Get product ID
GET http://localhost:5000/api/v1/productos/6590b1a5724f74672e1ac103

### Delete product
DELETE http://localhost:5000/api/v1/productos/658e18d5a1cedb9d56a3372e

### Post product
POST http://localhost:5000/api/v1/productos
Content-Type: application/json

{
  "title": "Men Cat Whisker Straight Leg Jeans",
  "description": "I discovered amazing products on SHEIN.com, come check them out!",
  "image": "https://i.pinimg.com/564x/1c/e0/53/1ce053123bfaf353dcd5e51611e539ea.jpg",
  "price": 87.99,
  "stock": true
}