### Get users
GET http://localhost:5000/api/v1/usuarios

### Post user
POST http://localhost:5000/api/v1/usuarios
Content-Type: application/json

{
  "email": "lucho@hotmail.com",
  "password": "123456789",
  "direccion": "direccion lucho"
}